### ISSUE TITLE
Im setting Text from Programatically it is not working for me

### ISSUE THREAD

**Issue by vaibbhavsar** [mahimrocky/ShowMoreText#1]
First I want to say thanx for this Lib.

I'm facing the issue in given API.

When I set text from XML it is working fine for me and Readmore and ReadLess is working fine for me

But while set Text programmatically then it is giving Issue for me, Even ReadLess and ReadMore both keys are Hidden for me

Please Help 
Thanx in advance

**Comment by mahimrocky** [comment]
Thank you for you issue. Now the is solved
