### ISSUE TITLE
Request support for state saving and recovery

### ISSUE THREAD

**Issue by tcqq** [mahimrocky/ShowMoreText#2]
@mahimrocky The collapsed or expanded state does not save and resume when the activity is reset.

**Comment by mahimrocky** [comment]
Yes. I will add a support for saving state next version.

**Comment by mahimrocky** [comment]
This issue is solved update version 1.0.2

**Comment by tcqq** [comment]
@mahimrocky  I tested it, but there is a problem at the moment:

First click on the "Continue" button to expand the text
![1](https://user-images.githubusercontent.com/10644057/57192276-3ac4d600-6f61-11e9-86a9-5fd62fb587c0.jpg)

This is before reset activity the screenshot
![2](https://user-images.githubusercontent.com/10644057/57192278-3c8e9980-6f61-11e9-9317-a985607bd761.jpg)

This is after reset activity the screenshot. The button text has changed now.
![3](https://user-images.githubusercontent.com/10644057/57192280-3ef0f380-6f61-11e9-82d4-4387d44f9bc1.jpg)

Now fold the text
![4](https://user-images.githubusercontent.com/10644057/57192283-40222080-6f61-11e9-9d0b-cf03439e1928.jpg)

Then expand the text. The button text has changed now.
![5](https://user-images.githubusercontent.com/10644057/57192284-41ebe400-6f61-11e9-80cc-7f3f11443574.jpg)
